version: '3.8'

services:
  jenkins-blueocean:
    image: jenkins/jenkins:lts
    container_name: jenkins-blueocean
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jenkins_db
      POSTGRES_USER: jenkins_user
      POSTGRES_PASSWORD: jenkins_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Mapping PostgreSQL service port 5432 to host port 9000
    networks:
      - jenkins

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
  postgres-data:
